stages:
  - test

test_suite_1:
  stage: test
  image: joyzoursky/python-chromedriver:3.6
  before_script:
    - pip install -r ./requirements.txt
  script:
    - robot -d ./results  $TAG .
  artifacts:
    when: always
    paths:
        - ./results
    expire_in: 1 week

after_script:
    - python  Libraries/request.py